# Generated by Django 4.2.23 on 2025-07-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='season_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('best_months', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='TripMate_app.season')),
            ],
        ),
    ]
