# Generated by Django 4.2.23 on 2025-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
